# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'dev-hyscale-jenkins-artifactory'
    sourceFolder: '$(Agent.BuildDirectory)/s/target'
    contents: '**/*.war'
    targetFolder: '/tmp/$(Build.BuildNumber)'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hyscalectl-jumpbox'
    sourceFolder: '$(Agent.BuildDirectory)/s/hyscale'
    contents: '**'
    targetFolder: '/tmp/$(Build.BuildNumber)/hyscale'
- task: SSH@0
  inputs:
    sshEndpoint: 'hyscalectl-jumpbox'
    runOptions: 'commands'
    commands: '/bin/sed -i "s/@@BUILD_NUMBER@@/$(Build.BuildNumber)/g" /tmp/$(Build.BuildNumber)/hyscale/dev-props.yaml /tmp/$(Build.BuildNumber)/hyscale/stage-props.yaml /tmp/$(Build.BuildNumber)/hyscale/prod-props.yaml'

