/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.hrdb.models.query.*;

@Service
public class HrdbQueryExecutorServiceImpl_V1 implements HrdbQueryExecutorService_V1 {

    private static final Logger LOGGER = LoggerFactory.getLogger(HrdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("hrdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeChecking(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("checking", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmploteeList(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmploteeList", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeSelectVar(Pageable pageable, Integer selectedEmployee) {
        Map params = new HashMap(1);

        params.put("SelectedEmployee", selectedEmployee);

        return queryExecutor.executeNamedQuery("EmployeeSelectVar", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSearchEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SearchEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSelectEmployee(Pageable pageable, Integer searchId, Integer liveListId) {
        Map params = new HashMap(2);

        params.put("SearchID", searchId);
        params.put("LiveListID", liveListId);

        return queryExecutor.executeNamedQuery("SelectEmployee", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeListOf_DeptId2(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmployeeListOf_DeptId2", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeListOf_Deptid3(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmployeeListOf_Deptid3", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeListOf_DeptId1(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmployeeListOf_DeptId1", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeDepartmentCount(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("DepartmentCount", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSrv_Var_EmployeeCount(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("Srv_Var_EmployeeCount", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> execute_ColleagueDetails(Pageable pageable, Integer selectedemployeedeptid, Integer selectedemployeeid) {
        Map params = new HashMap(2);

        params.put("selectedemployeedeptid", selectedemployeedeptid);
        params.put("selectedemployeeid", selectedemployeeid);

        return queryExecutor.executeNamedQuery("_ColleagueDetails", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSelectEmployeeVar(Pageable pageable, Integer searchId, Integer liveListId) {
        Map params = new HashMap(2);

        params.put("SearchID", searchId);
        params.put("LiveListID", liveListId);

        return queryExecutor.executeNamedQuery("SelectEmployeeVar", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeListOf_DeptId4(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmployeeListOf_DeptId4", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeNoOfDepartment(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("NoOfDepartment", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeTotalBudget(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("TotalBudget", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEmployeeListOf_DeptId5(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EmployeeListOf_DeptId5", params, Object.class, pageable);
    }

}