/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<CheckingResponse> executeChecking(Pageable pageable);

    void exportChecking(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmploteeListResponse> executeEmploteeList(Pageable pageable);

    void exportEmploteeList(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeSelectVarResponse> executeEmployeeSelectVar(Integer selectedEmployee, Pageable pageable);

    void exportEmployeeSelectVar(Integer selectedEmployee, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SearchEmployeesResponse> executeSearchEmployees(Pageable pageable);

    void exportSearchEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SelectEmployeeResponse> executeSelectEmployee(Integer searchId, Integer liveListId, Pageable pageable);

    void exportSelectEmployee(Integer searchId, Integer liveListId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeListOfDeptId2Response> executeEmployeeListOf_DeptId2(Pageable pageable);

    void exportEmployeeListOf_DeptId2(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeListOfDeptid3Response> executeEmployeeListOf_Deptid3(Pageable pageable);

    void exportEmployeeListOf_Deptid3(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeListOfDeptId1Response> executeEmployeeListOf_DeptId1(Pageable pageable);

    void exportEmployeeListOf_DeptId1(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<DepartmentCountResponse> executeDepartmentCount(Pageable pageable);

    void exportDepartmentCount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SrvVarEmployeeCountResponse> executeSrv_Var_EmployeeCount(Pageable pageable);

    void exportSrv_Var_EmployeeCount(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<ColleagueDetailsResponse> execute_ColleagueDetails(Integer selectedemployeedeptid, Integer selectedemployeeid, Pageable pageable);

    void export_ColleagueDetails(Integer selectedemployeedeptid, Integer selectedemployeeid, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SelectEmployeeVarResponse> executeSelectEmployeeVar(Integer searchId, Integer liveListId, Pageable pageable);

    void exportSelectEmployeeVar(Integer searchId, Integer liveListId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeListOfDeptId4Response> executeEmployeeListOf_DeptId4(Pageable pageable);

    void exportEmployeeListOf_DeptId4(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<NoOfDepartmentResponse> executeNoOfDepartment(Pageable pageable);

    void exportNoOfDepartment(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TotalBudgetResponse> executeTotalBudget(Pageable pageable);

    void exportTotalBudget(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EmployeeListOfDeptId5Response> executeEmployeeListOf_DeptId5(Pageable pageable);

    void exportEmployeeListOf_DeptId5(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}