/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class DepartmentCountResponse implements Serializable {


    @JsonProperty("COUNT(NAME)")
    @ColumnAlias("COUNT(NAME)")
    private Long count_name_;

    public Long getCount_name_() {
        return this.count_name_;
    }

    public void setCount_name_(Long count_name_) {
        this.count_name_ = count_name_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DepartmentCountResponse)) return false;
        final DepartmentCountResponse departmentCountResponse = (DepartmentCountResponse) o;
        return Objects.equals(getCount_name_(), departmentCountResponse.getCount_name_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount_name_());
    }
}