/*Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SrvVarEmployeeCountResponse implements Serializable {


    @JsonProperty("COUNT(eid)")
    @ColumnAlias("COUNT(eid)")
    private Long count_eid_;

    public Long getCount_eid_() {
        return this.count_eid_;
    }

    public void setCount_eid_(Long count_eid_) {
        this.count_eid_ = count_eid_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SrvVarEmployeeCountResponse)) return false;
        final SrvVarEmployeeCountResponse srvVarEmployeeCountResponse = (SrvVarEmployeeCountResponse) o;
        return Objects.equals(getCount_eid_(), srvVarEmployeeCountResponse.getCount_eid_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount_eid_());
    }
}